from pathlib import Path


def test_readme_links_final_quickstart():
    readme = Path("README.md").read_text(encoding="utf-8")

    assert "docs/quickstart.md" in readme


def test_quickstart_documents_minimum_verified_run_path():
    text = Path("docs/quickstart.md").read_text(encoding="utf-8")

    required_snippets = [
        "GeneFamilyFlow",
        "/usr/local/bin/R",
        "species bank",
        "python bin/genefam/run_release_checks.py --outdir results/release_checks",
        "Required failed",
        "Optional failed",
        "python bin/genefam/run_quickstart.py",
        "--outdir results/quickstart",
        "results/quickstart/quickstart_summary.md",
        "python bin/genefam/audit_objective_completion.py",
        "results/objective_audit/objective_audit.md",
        "results/handoff/handoff_report.md",
        "results/local_acceptance/local_acceptance_summary.md",
        "results/publication_report_audit/publication_report_audit.md",
        "results/publication_report_audit/wgd_publication_report_audit.md",
        "results/report_index_audit/standard_report_index_audit.md",
        "results/report_index_audit/wgd_report_index_audit.md",
        "publication_report_audit",
        "wgd_publication_report_audit",
        "standard_report_index_audit",
        "wgd_report_index_audit",
        "report-index audit exit status",
        "final_stage_blocker",
        "Overall status: blocked",
        "paper-style report closure",
        "WGD report closure",
        "report-index closure",
        "figure_interpretations.md",
        "final_report.md",
        "valid plot file signatures",
        "registered-only figure interpretation scope",
        "plot manifest and interpretation output path consistency",
        "complete per-figure close-reading text",
        "result-statement observations rather than instructional prompts",
        "QC tables and warnings",
        "software/R package versions",
        "per-figure method/software version coverage",
        "reproducibility commands",
        "results/delivery_bundle/delivery_manifest.tsv",
        "results/delivery_bundle/delivery_bundle.md",
        "results/delivery_bundle/figure_gallery.tsv",
        "results/delivery_bundle/figure_gallery.md",
        "r_runtime_health",
        "results/r_runtime_health/r_runtime_health.md",
        "audit_figure_gallery.py",
        "results/delivery_bundle_smoke/figure_gallery_audit.tsv",
        "results/delivery_bundle_smoke/figure_gallery_audit.md",
        "audit_delivery_manifest.py",
        "results/delivery_bundle_smoke/delivery_manifest_audit.tsv",
        "results/delivery_bundle_smoke/delivery_manifest_audit.md",
        "results/delivery_bundle/final_delivery_manifest_audit.tsv",
        "results/delivery_bundle/final_delivery_manifest_audit.md",
        "local acceptance summary",
        "figure_gallery_audit",
        "valid gallery plot file signatures",
        "delivery_manifest_audit",
        "final_delivery_manifest_audit",
        "figure_traceability_matrix",
        "global paper-level figure gallery",
        "configs/manifest.example.yaml",
        "primary species-bank YAML entrypoint",
        "configs/example.config.yaml",
        "primary WGD event YAML entrypoint",
        "configs/wgd_events.brassicaceae.yaml",
        "tests/fixtures/species_manifest.tsv",
        "results/species_manifest_selection_smoke/tables/species_manifest.tsv",
        "results/nextflow_standard_manifest_smoke/nextflow_standard_smoke.tsv",
        "python bin/genefam/run_standard_smoke.py",
        "python bin/genefam/run_nextflow_single_tool_smoke.py",
        "--config configs/example.config.yaml",
        "--groups configs/species_groups.yaml",
        "--mock-evidence-dir tests/fixtures/mock_evidence",
        "--outdir results/standard_smoke",
        "--outdir results/nextflow_single_tool_smoke",
        "nextflow_standard_hmmer_only",
        "nextflow_standard_diamond_only",
        "python bin/genefam/run_prepared_wgd_handoff_example.py",
        "--example-dir examples/prepared_wgd_handoff",
        "--outdir results/example_prepared_wgd",
        "results/standard_smoke/report/final_report.md",
        "results/standard_smoke/tables/wgd_handoff_manifest.tsv",
        "results/quickstart/standard_smoke/tables/run_config_snapshot.tsv",
        "results/example_prepared_wgd/report/final_report.md",
        "results/quickstart/example_prepared_wgd/tables/wgd_run_config_snapshot.tsv",
        "Run Configuration Snapshot",
        "results/example_prepared_wgd/tables/wgd_event_evidence.tsv",
        "alpha",
        "beta",
        "gamma",
        "theta",
        "docker",
        "apptainer",
        "bash results/readiness/runtime_bootstrap.sh",
        "genefam-pipeline_latest.sif",
        "HISTORY.md",
        "Reference/",
    ]
    for snippet in required_snippets:
        assert snippet in text
