import subprocess
import sys

from bin.genefam.build_standard_report_index import build_report_index, published_paths, read_tsv


def test_build_standard_report_index_marks_core_outputs_available():
    rows = build_report_index(
        {
            "species_manifest": "tables/species_manifest.tsv",
            "run_config_snapshot": "tables/run_config_snapshot.tsv",
            "family_candidates": "tables/family_candidates.tsv",
            "family_counts": "tables/family_counts.tsv",
            "family_members_faa": "sequences/family_members.faa",
            "gene_family_copy_number": "tables/gene_family_copy_number.tsv",
            "gene_family_copy_number_summary": "tables/gene_family_copy_number_summary.tsv",
            "gene_family_species_order": "tables/gene_family_species_order.tsv",
            "gene_family_copy_number_expansion": "tables/gene_family_copy_number_expansion.tsv",
            "gene_family_pangenome_summary": "tables/gene_family_pangenome_summary.tsv",
            "gene_family_protein_properties": "tables/gene_family_protein_properties.tsv",
            "gene_family_info_pdf": "plots/gene_family_info_summary.pdf",
            "gene_family_info_png": "plots/gene_family_info_summary.png",
            "alignment_manifest": "tables/alignment_manifest.tsv",
            "alignment_file": "alignment/GDSL.mafft.aln.faa",
            "phylogeny_manifest": "tables/phylogeny_manifest.tsv",
            "phylogeny_tree": "phylogeny/GDSL.fasttree.treefile",
            "motif_summary": "tables/motif_summary.tsv",
            "gene_structure_summary": "tables/gene_structure_summary.tsv",
            "tree_feature_matrix": "tables/tree_feature_matrix.tsv",
            "tree_features_pdf": "plots/tree_features.pdf",
            "tree_features_png": "plots/tree_features.png",
            "chromosome_locations": "tables/chromosome_locations.tsv",
            "promoters_bed": "",
            "promoters_fasta": "",
            "promoter_cis_elements": "",
            "promoter_cis_gene_matrix": "",
            "promoter_cis_gene_element_matrix": "",
            "promoter_cis_category_summary": "",
            "promoter_cis_element_annotations": "",
            "promoter_cis_pdf": "",
            "promoter_cis_png": "",
            "feature_summary": "",
            "feature_summary_pdf": "",
            "feature_summary_png": "",
            "mcscanx_circlize_pdf": "",
            "mcscanx_circlize_png": "",
            "circlize_link_density": "",
            "circlize_duplicate_type_tracks": "",
            "ppi_edges": "",
            "ppi_nodes": "",
            "ppi_hubs": "",
            "ppi_input_evidence": "",
            "ppi_network_qc": "",
            "ppi_ggnetview_status": "",
            "ppi_ggnetview_pdf": "",
            "ppi_ggnetview_png": "",
            "family_expression": "",
            "expression_sample_metadata": "",
            "expression_group_matrix": "",
            "expression_gene_summary": "",
            "expression_heatmap_pdf": "",
            "expression_heatmap_png": "",
            "wgd_handoff_manifest": "tables/wgd_handoff_manifest.tsv",
            "plot_manifest": "tables/plot_manifest.tsv",
            "software_versions": "report/software_versions.tsv",
            "figure_interpretations": "report/figure_interpretations.tsv",
        }
    )

    assert rows[0] == {
        "key": "species_manifest",
        "path": "tables/species_manifest.tsv",
        "status": "available",
        "description": "Selected species and input files",
    }
    assert {row["key"] for row in rows} >= {
        "run_config_snapshot",
        "family_members_faa",
        "gene_family_copy_number",
        "gene_family_copy_number_summary",
        "gene_family_species_order",
        "gene_family_copy_number_expansion",
        "gene_family_pangenome_summary",
        "gene_family_protein_properties",
        "gene_family_info_pdf",
        "gene_family_info_png",
        "alignment_manifest",
        "alignment_file",
        "phylogeny_manifest",
        "phylogeny_tree",
        "motif_summary",
        "gene_structure_summary",
        "tree_feature_matrix",
        "tree_features_pdf",
        "tree_features_png",
        "chromosome_locations",
        "promoters_bed",
        "promoters_fasta",
        "promoter_cis_elements",
        "promoter_cis_gene_matrix",
        "promoter_cis_gene_element_matrix",
        "promoter_cis_category_summary",
        "promoter_cis_element_annotations",
        "promoter_cis_pdf",
        "promoter_cis_png",
        "feature_summary",
        "feature_summary_pdf",
        "feature_summary_png",
        "mcscanx_circlize_pdf",
        "mcscanx_circlize_png",
        "circlize_link_density",
        "circlize_duplicate_type_tracks",
        "ppi_edges",
        "ppi_nodes",
        "ppi_hubs",
        "ppi_input_evidence",
        "ppi_network_qc",
        "ppi_ggnetview_status",
        "ppi_ggnetview_pdf",
        "ppi_ggnetview_png",
        "family_expression",
        "expression_sample_metadata",
        "expression_group_matrix",
        "expression_gene_summary",
        "expression_heatmap_pdf",
        "expression_heatmap_png",
        "wgd_handoff_manifest",
        "software_versions",
        "figure_interpretations",
    }
    assert next(row for row in rows if row["key"] == "family_expression")["status"] == "missing"
    assert next(row for row in rows if row["key"] == "expression_heatmap_pdf")["status"] == "missing"
    assert next(row for row in rows if row["key"] == "promoters_bed")["status"] == "missing"
    assert next(row for row in rows if row["key"] == "promoter_cis_pdf")["status"] == "missing"
    assert next(row for row in rows if row["key"] == "promoter_cis_element_annotations")["status"] == "missing"
    assert next(row for row in rows if row["key"] == "feature_summary_pdf")["status"] == "missing"
    assert next(row for row in rows if row["key"] == "mcscanx_circlize_pdf")["status"] == "missing"
    assert next(row for row in rows if row["key"] == "circlize_link_density")["status"] == "missing"
    assert next(row for row in rows if row["key"] == "ppi_ggnetview_pdf")["status"] == "missing"


def test_published_paths_map_standard_outputs_to_user_results_tree():
    paths = published_paths("results/nextflow_standard_smoke/standard", family_expression_available=False)

    assert paths == {
        "species_manifest": "results/nextflow_standard_smoke/standard/tables/species_manifest.tsv",
        "run_config_snapshot": "results/nextflow_standard_smoke/standard/tables/run_config_snapshot.tsv",
        "family_candidates": "results/nextflow_standard_smoke/standard/tables/family_candidates.tsv",
        "family_counts": "results/nextflow_standard_smoke/standard/tables/family_counts.tsv",
        "family_members_faa": "results/nextflow_standard_smoke/standard/sequences/family_members.faa",
        "gene_family_copy_number": "results/nextflow_standard_smoke/standard/tables/gene_family_copy_number.tsv",
        "gene_family_copy_number_summary": "results/nextflow_standard_smoke/standard/tables/gene_family_copy_number_summary.tsv",
        "gene_family_species_order": "results/nextflow_standard_smoke/standard/tables/gene_family_species_order.tsv",
        "gene_family_copy_number_expansion": "results/nextflow_standard_smoke/standard/tables/gene_family_copy_number_expansion.tsv",
        "gene_family_pangenome_summary": "results/nextflow_standard_smoke/standard/tables/gene_family_pangenome_summary.tsv",
        "gene_family_protein_properties": "results/nextflow_standard_smoke/standard/tables/gene_family_protein_properties.tsv",
        "gene_family_info_pdf": "results/nextflow_standard_smoke/standard/plots/gene_family_info_summary.pdf",
        "gene_family_info_png": "results/nextflow_standard_smoke/standard/plots/gene_family_info_summary.png",
        "alignment_manifest": "results/nextflow_standard_smoke/standard/tables/alignment_manifest.tsv",
        "alignment_file": "results/nextflow_standard_smoke/standard/alignment/GDSL.mafft.aln.faa",
        "phylogeny_manifest": "results/nextflow_standard_smoke/standard/tables/phylogeny_manifest.tsv",
        "phylogeny_tree": "results/nextflow_standard_smoke/standard/phylogeny/GDSL.fasttree.treefile",
        "motif_summary": "results/nextflow_standard_smoke/standard/tables/motif_summary.tsv",
        "gene_structure_summary": "results/nextflow_standard_smoke/standard/tables/gene_structure_summary.tsv",
        "tree_feature_matrix": "results/nextflow_standard_smoke/standard/tables/tree_feature_matrix.tsv",
        "tree_features_pdf": "results/nextflow_standard_smoke/standard/plots/tree_features.pdf",
        "tree_features_png": "results/nextflow_standard_smoke/standard/plots/tree_features.png",
        "chromosome_locations": "results/nextflow_standard_smoke/standard/tables/chromosome_locations.tsv",
        "promoters_bed": "",
        "promoters_fasta": "",
        "promoter_cis_elements": "",
        "promoter_cis_gene_matrix": "",
        "promoter_cis_gene_element_matrix": "",
        "promoter_cis_category_summary": "",
        "promoter_cis_element_annotations": "",
        "promoter_cis_pdf": "",
        "promoter_cis_png": "",
        "feature_summary": "",
        "feature_summary_pdf": "",
        "feature_summary_png": "",
        "mcscanx_circlize_pdf": "",
        "mcscanx_circlize_png": "",
        "circlize_link_density": "",
        "circlize_duplicate_type_tracks": "",
        "ppi_edges": "",
        "ppi_nodes": "",
        "ppi_hubs": "",
        "ppi_input_evidence": "",
        "ppi_network_qc": "",
        "ppi_ggnetview_status": "",
        "ppi_ggnetview_pdf": "",
        "ppi_ggnetview_png": "",
        "family_expression": "",
        "expression_sample_metadata": "",
        "expression_group_matrix": "",
        "expression_gene_summary": "",
        "expression_heatmap_pdf": "",
        "expression_heatmap_png": "",
        "wgd_handoff_manifest": "results/nextflow_standard_smoke/standard/tables/wgd_handoff_manifest.tsv",
        "plot_manifest": "results/nextflow_standard_smoke/standard/report/plot_manifest.tsv",
        "software_versions": "results/nextflow_standard_smoke/standard/report/software_versions.tsv",
        "figure_interpretations": "results/nextflow_standard_smoke/standard/report/figure_interpretations.tsv",
    }


def test_build_standard_report_index_cli_writes_tsv(tmp_path):
    out = tmp_path / "report_index.tsv"

    completed = subprocess.run(
        [
            sys.executable,
            "bin/genefam/build_standard_report_index.py",
            "--species-manifest",
            "species_manifest.tsv",
            "--run-config-snapshot",
            "run_config_snapshot.tsv",
            "--family-candidates",
            "family_candidates.tsv",
            "--family-counts",
            "family_counts.tsv",
            "--family-members-faa",
            "family_members.faa",
            "--gene-family-copy-number",
            "gene_family_copy_number.tsv",
            "--gene-family-copy-number-summary",
            "gene_family_copy_number_summary.tsv",
            "--gene-family-species-order",
            "gene_family_species_order.tsv",
            "--gene-family-copy-number-expansion",
            "gene_family_copy_number_expansion.tsv",
            "--gene-family-pangenome-summary",
            "gene_family_pangenome_summary.tsv",
            "--gene-family-protein-properties",
            "gene_family_protein_properties.tsv",
            "--gene-family-info-pdf",
            "gene_family_info_summary.pdf",
            "--gene-family-info-png",
            "gene_family_info_summary.png",
            "--alignment-manifest",
            "alignment_manifest.tsv",
            "--alignment-file",
            "GDSL.mafft.aln.faa",
            "--phylogeny-manifest",
            "phylogeny_manifest.tsv",
            "--phylogeny-tree",
            "GDSL.fasttree.treefile",
            "--motif-summary",
            "motif_summary.tsv",
            "--gene-structure-summary",
            "gene_structure_summary.tsv",
            "--tree-feature-matrix",
            "tree_feature_matrix.tsv",
            "--tree-features-pdf",
            "tree_features.pdf",
            "--tree-features-png",
            "tree_features.png",
            "--chromosome-locations",
            "chromosome_locations.tsv",
            "--family-expression",
            "",
            "--expression-sample-metadata",
            "",
            "--expression-group-matrix",
            "",
            "--expression-gene-summary",
            "",
            "--expression-heatmap-pdf",
            "",
            "--expression-heatmap-png",
            "",
            "--wgd-handoff-manifest",
            "wgd_handoff_manifest.tsv",
            "--plot-manifest",
            "plot_manifest.tsv",
            "--software-versions",
            "software_versions.tsv",
            "--figure-interpretations",
            "figure_interpretations.tsv",
            "--out",
            str(out),
        ],
        check=False,
        capture_output=True,
        text=True,
    )

    assert completed.returncode == 0, completed.stderr
    assert read_tsv(out)[-1] == {
        "key": "figure_interpretations",
        "path": "figure_interpretations.tsv",
        "status": "available",
        "description": "Structured per-figure result interpretation notes",
    }


def test_build_standard_report_index_cli_can_write_published_paths(tmp_path):
    out = tmp_path / "report_index.tsv"

    completed = subprocess.run(
        [
            sys.executable,
            "bin/genefam/build_standard_report_index.py",
            "--species-manifest",
            "species_manifest.tsv",
            "--run-config-snapshot",
            "run_config_snapshot.tsv",
            "--family-candidates",
            "family_candidates.tsv",
            "--family-counts",
            "family_counts.tsv",
            "--family-members-faa",
            "family_members.faa",
            "--gene-family-copy-number",
            "gene_family_copy_number.tsv",
            "--gene-family-copy-number-summary",
            "gene_family_copy_number_summary.tsv",
            "--gene-family-species-order",
            "gene_family_species_order.tsv",
            "--gene-family-copy-number-expansion",
            "gene_family_copy_number_expansion.tsv",
            "--gene-family-pangenome-summary",
            "gene_family_pangenome_summary.tsv",
            "--gene-family-protein-properties",
            "gene_family_protein_properties.tsv",
            "--gene-family-info-pdf",
            "gene_family_info_summary.pdf",
            "--gene-family-info-png",
            "gene_family_info_summary.png",
            "--alignment-manifest",
            "alignment_manifest.tsv",
            "--alignment-file",
            "GDSL.mafft.aln.faa",
            "--phylogeny-manifest",
            "phylogeny_manifest.tsv",
            "--phylogeny-tree",
            "GDSL.fasttree.treefile",
            "--motif-summary",
            "motif_summary.tsv",
            "--gene-structure-summary",
            "gene_structure_summary.tsv",
            "--tree-feature-matrix",
            "tree_feature_matrix.tsv",
            "--tree-features-pdf",
            "tree_features.pdf",
            "--tree-features-png",
            "tree_features.png",
            "--chromosome-locations",
            "chromosome_locations.tsv",
            "--family-expression",
            "",
            "--expression-sample-metadata",
            "",
            "--expression-group-matrix",
            "",
            "--expression-gene-summary",
            "",
            "--expression-heatmap-pdf",
            "",
            "--expression-heatmap-png",
            "",
            "--wgd-handoff-manifest",
            "wgd_handoff_manifest.tsv",
            "--plot-manifest",
            "plot_manifest.tsv",
            "--software-versions",
            "software_versions.tsv",
            "--figure-interpretations",
            "figure_interpretations.tsv",
            "--published-outdir",
            "results/demo",
            "--out",
            str(out),
        ],
        check=False,
        capture_output=True,
        text=True,
    )

    assert completed.returncode == 0, completed.stderr
    rows = {row["key"]: row for row in read_tsv(out)}
    assert rows["family_candidates"]["path"] == "results/demo/tables/family_candidates.tsv"
    assert rows["run_config_snapshot"]["path"] == "results/demo/tables/run_config_snapshot.tsv"
    assert rows["family_members_faa"]["path"] == "results/demo/sequences/family_members.faa"
    assert rows["gene_family_info_pdf"]["path"] == "results/demo/plots/gene_family_info_summary.pdf"
    assert rows["gene_family_species_order"]["path"] == "results/demo/tables/gene_family_species_order.tsv"
    assert rows["gene_family_copy_number_expansion"]["path"] == "results/demo/tables/gene_family_copy_number_expansion.tsv"
    assert rows["gene_family_pangenome_summary"]["path"] == "results/demo/tables/gene_family_pangenome_summary.tsv"
    assert rows["alignment_file"]["path"] == "results/demo/alignment/GDSL.mafft.aln.faa"
    assert rows["phylogeny_tree"]["path"] == "results/demo/phylogeny/GDSL.fasttree.treefile"
    assert rows["motif_summary"]["path"] == "results/demo/tables/motif_summary.tsv"
    assert rows["gene_structure_summary"]["path"] == "results/demo/tables/gene_structure_summary.tsv"
    assert rows["tree_feature_matrix"]["path"] == "results/demo/tables/tree_feature_matrix.tsv"
    assert rows["tree_features_pdf"]["path"] == "results/demo/plots/tree_features.pdf"
    assert rows["tree_features_png"]["path"] == "results/demo/plots/tree_features.png"
    assert rows["wgd_handoff_manifest"]["path"] == "results/demo/tables/wgd_handoff_manifest.tsv"
    assert rows["plot_manifest"]["path"] == "results/demo/report/plot_manifest.tsv"
    assert rows["software_versions"]["path"] == "results/demo/report/software_versions.tsv"
    assert rows["figure_interpretations"]["path"] == "results/demo/report/figure_interpretations.tsv"
