project:
  name: Whirly_2026
  root: projects/Whirly_2026
  outdir: projects/Whirly_2026/results

database:
  species_clean_bank: projects/Whirly_2026/results/01_preprocess/species_clean_bank

species:
  include: []
  exclude: []

modules:
  preprocess: true
  hmm: true
  blastp: true
  identification: true
  genefamily_info: true
  phylogeny: true

hmm:
  hmm_dir: projects/Whirly_2026/config/hmm_profiles
  combine_rule: any
  evalue: 1.0e-10
  min_bitscore: 0.0
  min_domain_coverage: 0.0
  rebuild_hmm: true
  family_name: Whirly

blastp:
  domain_terms:
    - PF08536
  reference_sources: configs/03_blastp/reference_sources.tsv
  evalue: 1.0e-10
  num_threads: 10
  num_alignments: 10

identification:
  final_rule: intersection
  domain_method: hmmsearch
  domain_terms:
    - PF08536
  domain_evalue: 1.0e-5
  pfam_scan_executable: pfam_scan.pl
  pfam_scan_dir: ""

genefamily_info:
  plot: true
  r_bin: /usr/local/bin/R

phylogeny:
  family_name: Whirly
  aligner: muscle
  aligner_options:
    - -super5
    - "{input}"
    - -output
    - "{output}"
  tree_builder: fasttree
  fasttree_options:
    - -lg
  threads: AUTO
  iqtree_model: MFP
  iqtree_bootstrap: 1000
  iqtree_options:
    - -bnni
    - -cmax
    - "15"
    - -redo
  subfamily:
    enabled: true
    method: auto_topology
    min_size: 2
    max_groups: 8
    r_bin: /usr/local/bin/R
